# Generated by Django 4.2.3 on 2023-07-17 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEPARTMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='Mobile_Number',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
    ]
