# Generated by Django 4.2.3 on 2023-07-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_department_alter_user_mobile_number_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Description',
            field=models.TextField(null=True),
        ),
    ]
